site_name: RL-IDS Adaptive System
site_description: Reinforcement Learning-driven Adaptive Intrusion Detection System with real-time threat detection capabilities
site_author: Yash Yogesh Potdar
site_url: https://yashpotdar-py.github.io/rl-ids

# Repository
repo_name: yashpotdar-py/rl-ids
repo_url: https://github.com/yashpotdar-py/rl-ids
edit_uri: edit/main/docs/docs/

copyright: Copyright &copy; 2025 Yash Yogesh Potdar. All rights reserved

theme:
  name: shadcn

# Navigation
nav:
  - Home: index.md
  - User Guide:
      - Overview: user-guide/index.md
      - Installation: user-guide/installation.md
      - Network Monitoring: user-guide/network-monitoring.md
      - Website Monitoring: user-guide/website-monitoring.md
  - API Reference:
      - Overview: api/index.md
      - Python Client: api/python-client.md
      - Examples: api/examples.md
  - Modules:
      - Core Components: modules/index.md
      - RL Agents: modules/agents.md
      - Feature Extraction: modules/features.md
  - Development:
      - Contributing: development/contributing.md
      - Architecture: development/architecture.md
      - Testing: development/testing.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - LICENSE: license.md
